default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: postgres
  password: 


development:
  <<: *default
  database: blog

test:
  <<: *default

production:
  <<: *default
